"""
Fuzzing at the HTTP boundary (plan section 2.5's Hypothesis approach,
applied one layer up): tests/property/ drives adversarial inputs straight
into pure functions; this drives them through the real endpoint --
request parsing, Pydantic coercion, and the DB layer all included.

The property under test throughout: a malformed/adversarial request must
get a clean 4xx response (validation or auth failure), never a 500.
Nothing here asserts a SPECIFIC 4xx code for the generated cases -- the
point is discovering whether anything slips through uncaught, not
re-checking Pydantic's already-known rules.

Note: this is NOT expected to guarantee zero bids ever get created. Some
generated values (e.g. a numeric string, or a very large integer) are
genuinely valid bids -- validate_bid has no upper bound on amount -- and
correctly succeeding is correct behavior, not a fuzzing "win". What must
never happen is a 500, or a CORRUPTED bid making it into the DB (see the
final sanity check below).
"""

import json
import uuid
from datetime import datetime, timedelta, timezone
from decimal import Decimal

import pytest
from hypothesis import given, settings, strategies as st

from app.db.database import SessionLocal
from app.models.user import User
from app.models.wallet import Wallet
from app.models.item import Item
from app.models.auction import Auction
from app.models.bid import Bid
from app.models.notification import Notification
from app.models.audit_log import AuditLogEntry
from app.core.auth import hash_password, create_access_token

from tests.integration.conftest import client


@pytest.fixture(scope="module")
def fuzz_target():
    """One committed seller/bidder/auction, reused read-only across every
    fuzz case in this file -- these requests should all fail validation
    before ever touching the DB, so there's nothing to reset between
    cases (verified explicitly by the no-stray-bids test below)."""
    db = SessionLocal()
    seller = User(
        first_name="Seller", last_name="Fuzz", email=f"{uuid.uuid4()}@example.test",
        password_hash=hash_password("x"),
    )
    bidder = User(
        first_name="Bidder", last_name="Fuzz", email=f"{uuid.uuid4()}@example.test",
        password_hash=hash_password("x"),
    )
    db.add_all([seller, bidder])
    db.flush()
    db.add_all([
        Wallet(user_id=seller.id, balance=Decimal("0"), held_amount=Decimal("0")),
        Wallet(user_id=bidder.id, balance=Decimal("1000.00"), held_amount=Decimal("0")),
    ])
    item = Item(title="Fuzz Target Item", description="d", category="Gaming", seller_id=seller.id)
    db.add(item)
    db.flush()
    now = datetime.now(timezone.utc)
    auction = Auction(
        item_id=item.id, starting_price=Decimal("50.00"), reserve_price=None,
        current_price=Decimal("50.00"), start_time=now - timedelta(hours=1),
        end_time=now + timedelta(hours=1), status="Active",
    )
    db.add(auction)
    db.commit()

    ids = dict(
        seller_id=seller.id, bidder_id=bidder.id, item_id=item.id, auction_id=auction.id,
        token=create_access_token(bidder.id),
    )
    db.close()

    yield ids

    cleanup = SessionLocal()
    user_ids = [ids["seller_id"], ids["bidder_id"]]
    # A fuzz case can legitimately succeed (e.g. a huge-but-valid amount),
    # which logs an audit entry and possibly a notification -- both must
    # be cleared before the users/auction they reference can be deleted.
    cleanup.query(Notification).filter(Notification.auction_id == ids["auction_id"]).delete()
    cleanup.query(AuditLogEntry).filter(AuditLogEntry.user_id.in_(user_ids)).delete(synchronize_session=False)
    cleanup.query(Bid).filter(Bid.auction_id == ids["auction_id"]).delete()
    cleanup.query(Auction).filter(Auction.id == ids["auction_id"]).delete()
    cleanup.query(Item).filter(Item.id == ids["item_id"]).delete()
    cleanup.query(Wallet).filter(Wallet.user_id.in_(user_ids)).delete(synchronize_session=False)
    cleanup.query(User).filter(User.id.in_(user_ids)).delete(synchronize_session=False)
    cleanup.commit()
    cleanup.close()


# Deliberately restricted to values that should ALWAYS be rejected --
# large-but-otherwise-ordinary positive numbers are excluded on purpose,
# since validate_bid has no upper bound on bid amount and a big enough
# positive number is a legitimately valid bid, not an adversarial one
# (an earlier version of this generator included unbounded positive
# integers and, correctly, produced one real accepted bid -- a good
# reminder that "generated by a fuzzer" isn't the same as "invalid").
# NaN/Infinity are handled separately below via raw request bodies --
# httpx's json= parameter refuses to serialize them at all (raises
# ValueError before the request is even sent), so they can't go through
# Hypothesis's json= path here.
adversarial_amount = st.one_of(
    st.integers(max_value=0),  # zero and negative
    st.floats(min_value=-1e10, max_value=0, allow_nan=False, allow_infinity=False),
    st.text(max_size=50),
    st.none(),
    st.booleans(),
    st.lists(st.integers(), max_size=3),
    st.dictionaries(st.text(max_size=5), st.integers(), max_size=3),
)


@settings(max_examples=60, deadline=None)
@given(amount=adversarial_amount)
def test_bid_endpoint_never_returns_500_for_adversarial_amount(fuzz_target, amount):
    resp = client.post(
        f"/auctions/{fuzz_target['auction_id']}/bids",
        json={"amount": amount},
        headers={"Authorization": f"Bearer {fuzz_target['token']}"},
    )
    assert resp.status_code < 500, (
        f"amount={amount!r} produced a server error: {resp.status_code} {resp.text}"
    )


@pytest.mark.parametrize(
    "raw_body, content_type",
    [
        (b"not json at all", "application/json"),
        (b"", "application/json"),
        (b"{", "application/json"),
        (b'{"amount": 55.00,}', "application/json"),  # trailing comma
        (b'{"amount": 55.00}' + b"\x00" * 10, "application/json"),  # embedded nulls
        (json.dumps({"amount": "55.00", "unexpected_field": "x" * 10000}).encode(), "application/json"),
        (b'{"amount": NaN}', "application/json"),  # non-standard JSON httpx's json= won't send
        (b'{"amount": Infinity}', "application/json"),
        (b'{"amount": -Infinity}', "application/json"),
    ],
)
def test_bid_endpoint_never_returns_500_for_malformed_request_bodies(fuzz_target, raw_body, content_type):
    resp = client.post(
        f"/auctions/{fuzz_target['auction_id']}/bids",
        content=raw_body,
        headers={
            "Authorization": f"Bearer {fuzz_target['token']}",
            "Content-Type": content_type,
        },
    )
    assert resp.status_code < 500, f"body={raw_body!r} produced: {resp.status_code} {resp.text}"


@pytest.mark.parametrize(
    "auth_header",
    [
        "not a bearer token at all",
        "Bearer ",
        "Bearer " + "x" * 5000,
        "Bearer " + create_access_token(uuid.uuid4()),  # well-formed JWT, nonexistent user
    ],
)
def test_bid_endpoint_never_returns_500_for_malformed_auth(fuzz_target, auth_header):
    resp = client.post(
        f"/auctions/{fuzz_target['auction_id']}/bids",
        json={"amount": "55.00"},
        headers={"Authorization": auth_header},
    )
    assert resp.status_code < 500, f"auth={auth_header!r} produced: {resp.status_code} {resp.text}"
    assert resp.status_code in (401, 403)


def test_any_bids_that_did_get_created_are_well_formed(fuzz_target):
    """Some fuzz cases above may legitimately succeed (a numeric string
    or a very large integer is a genuinely valid bid). That's correct
    behavior, not a bug. What must never happen is a fuzzed value
    sneaking through as a CORRUPTED bid -- a non-positive amount, or a
    status outside the known enum."""
    db = SessionLocal()
    bids = db.query(Bid).filter(Bid.auction_id == fuzz_target["auction_id"]).all()
    db.close()
    for bid in bids:
        assert bid.amount > 0
        assert bid.status in ("active", "outbid", "withdrawn")
